name: Publish
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        # If caches were enabled, it was caching Python 3.8 interpreter
        # causing the docs build to fails
        with:
          python-version: '3.10'      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true      
      - name: Install dependencies
        run: |
          poetry env use '3.10' 
          poetry install --no-interaction
      - name: Sphinx build
        run: |
          poetry env use '3.10' 
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true
